# Reference: http://wiki.ros.org/navigation/Tutorials/RobotSetup

obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.15, -0.15], [-0.15, 0.15], [0.15, 0.15], [0.15, -0.15]]

inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: simple4wd/base_hokuyo_link, data_type: LaserScan, topic: /simple4wd/laser/scan, marking: true, clearing: true}