# Reference: http://wiki.ros.org/navigation/Tutorials/RobotSetup

obstacle_range: 4.5
raytrace_range: 5

footprint: [[-0.15, -0.15], [-0.15, 0.15], [0.15, 0.15], [0.15, -0.15]]
footprint_padding: 0.05

plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: laser_scan_sensor depth_camera_sensor
  laser_scan_sensor: {sensor_frame: simple4wd/base_hokuyo_link, data_type: LaserScan, topic: /simple4wd/laser/scan, marking: true, clearing: false}
  depth_camera_sensor: {sensor_frame: simple4wd/kinect_camera_link, data_type: PointCloud2, topic: /simple4wd/kinect_camera/depth/points, marking: true, clearing: true}

inflater_layer:
  inflation_radius: 0.55

static:
  map_topic: map
  subscribe_to_updates: true

# inflation_radius: 0.55

# observation_sources: laser_scan_sensor

# laser_scan_sensor: {sensor_frame: simple4wd/base_hokuyo_link, data_type: LaserScan, topic: /simple4wd/laser/scan, marking: true, clearing: true}