<?xml version="1.0"?>

<robot name="simple4wd" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import urdf.xacro files -->
  <xacro:include filename="$(find simple4wd_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find simple4wd_description)/urdf/accessories/hokuyo_laser.urdf.xacro" />

  <!-- ROS Control Plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/simple4wd</robotNamespace>
    </plugin>
  </gazebo>

  <!-- Constants -->
  <xacro:property name="BASE_WIDTH" value="0.3"/> <!-- x -->
  <xacro:property name="BASE_LENGTH" value="0.3"/> <!-- y -->
  <xacro:property name="BASE_HEIGHT" value="0.05"/> <!-- z -->
  <xacro:property name="BASE_MASS" value="10"/>

  <xacro:property name="WHEEL_WIDTH" value="0.01"/>
  <xacro:property name="WHEEL_RADIUS" value="0.03"/>
  <xacro:property name="WHEEL_MASS" value="2"/>

  <xacro:property name="PI" value="3.14159"/>

  <!-- Materials -->
  <material name="cyan">
    <color rgba="0 1.0 1.0 1.0"/>
  </material>

  <!-- Dummy link that doesn't have inertia -->
  <link name="base_link" />

  <joint name="base_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <!-- Robot Base (front is facing positive x) -->
  <link name="chassis_link">
    <visual>
      <geometry>
        <box size="${BASE_WIDTH} ${BASE_LENGTH} ${BASE_HEIGHT}"/>
      </geometry>
      <material name="cyan"/>
    </visual>

    <collision>
      <geometry>
        <box size="${BASE_WIDTH} ${BASE_LENGTH} ${BASE_HEIGHT}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${BASE_MASS}"/>
      <inertia
        ixx="${BASE_MASS / 12.0 * (BASE_LENGTH * BASE_LENGTH + BASE_HEIGHT * BASE_HEIGHT)}" ixy="0" ixz="0"
        iyy="${BASE_MASS / 12.0 * (BASE_WIDTH * BASE_WIDTH + BASE_HEIGHT * BASE_HEIGHT)}" iyz="0"
        izz="${BASE_MASS / 12.0 * (BASE_WIDTH * BASE_WIDTH + BASE_LENGTH * BASE_LENGTH)}"
      />
    </inertial>
  </link>

  <!-- Wheels -->
  <xacro:wheel 
    name_link="left_front_wheel" parent_link="chassis_link"
    mass="${WHEEL_MASS}" radius="${WHEEL_RADIUS}" width="${WHEEL_WIDTH}"
    translate_x="${BASE_WIDTH/2 - 2*WHEEL_RADIUS}"
    translate_y="${BASE_LENGTH/2 + WHEEL_WIDTH/2}"
    translate_z="${-WHEEL_RADIUS}"
  />

  <xacro:wheel
    name_link="right_back_wheel" parent_link="chassis_link"
    mass="${WHEEL_MASS}" radius="${WHEEL_RADIUS}" width="${WHEEL_WIDTH}"
    translate_x="${-(BASE_WIDTH/2 - 2*WHEEL_RADIUS)}"
    translate_y="${-(BASE_LENGTH/2 + WHEEL_WIDTH/2)}"
    translate_z="${-WHEEL_RADIUS}"
  />

  <xacro:wheel
    name_link="right_front_wheel" parent_link="chassis_link"
    mass="${WHEEL_MASS}" radius="${WHEEL_RADIUS}" width="${WHEEL_WIDTH}"
    translate_x="${BASE_WIDTH/2 - 2*WHEEL_RADIUS}"
    translate_y="${-(BASE_LENGTH/2 + WHEEL_WIDTH/2)}"
    translate_z="${-WHEEL_RADIUS}"
  />

  <xacro:wheel
    name_link="left_back_wheel" parent_link="chassis_link"
    mass="${WHEEL_MASS}" radius="${WHEEL_RADIUS}" width="${WHEEL_WIDTH}"
    translate_x="${-(BASE_WIDTH/2 - 2*WHEEL_RADIUS)}"
    translate_y="${BASE_LENGTH/2 + WHEEL_WIDTH/2}"
    translate_z="${-WHEEL_RADIUS}"
  />

  <!-- Sensors -->
  <xacro:hokuyo_laser
    prefix="chassis" parent_link="chassis_link"
    trans_x="0" trans_y="0" trans_z="${BASE_HEIGHT}"
  />

</robot>